### ISSUE TITLE
Production mode

### ISSUE THREAD

**Issue by Anachron** [dbashford/mimosa.io#2]
Is there any reason why the website (mimosa.io) is run in development mode?
What I mean is, the files (css, js) are not combined and it creates one request per library.

If there is any reason why you do so in a productive environment, I would like be glad to hear it.

**Comment by dbashford** [comment]
It's just a static website.  So I don't stress it too much. =)

Someday I'll get around to using Mimosa to build the website, but its another low priority.

**Comment by Anachron** [comment]
First off, that was the fastest close I've seen so far on github! =)
Second, I didn't know that it was static, I supposed you created it with mimosa too,
since you even build Mimosa with Mimosa.

**Comment by dbashford** [comment]
I'd love to build it with Mimosa at some point, for sure.
