### ISSUE TITLE
Mention Skeletons on frontpage

### ISSUE THREAD

**Issue by Anachron** [dbashford/mimosa.io#3]
I was just thinking, isn't it a good start to mention the fast way how to start with Mimosa and EmberJS/AngularJS/Backbone and so on with skeletons?

Something like:
"Starting new apps made easy: Use your favorite skeleton to skip preparation time and spend more time on coding!"

Maybe it's a little boring since many frameworks do it now (emberjs.com, jquery.com, etc) but in my opinion it's very encouraging.

**Comment by dbashford** [comment]
Agreed, but lets discuss this in the other issue.
