### ISSUE TITLE
Command "bower:clean" description at Quick List: "Runs bower install."

### ISSUE THREAD

**Issue by jbruni** [dbashford/mimosa.io#6]
The "Quick List" table of Commands describes "bower:clean" as "Runs bower install." - it is a repetition of the row immediately above, describing the "bower" command.
- https://github.com/dbashford/mimosa.io/blob/gh-pages/commands.html#L140-L149
- http://mimosa.io/commands.html

**Comment by dbashford** [comment]
Thanks for letting me know!  Most folks don't bother. =)

Should be addressed.
